// Aspire AppHost — orchestrates a SQL Server container + the sample
// Umbraco host that project-references the Analyzer RCL. Run with
// `dotnet run --project aspire/Analyzer.AppHost` for clone-and-go dev.
//
// Mirrors ../customizer/aspire/Customizer.AppHost/Program.cs.

var builder = DistributedApplication.CreateBuilder(args);

// SQL Server runs in a Docker container managed by Aspire.
// - Password is auto-generated by Aspire and persisted to user-secrets,
//   so it survives `dotnet run` restarts without manual config.
// - WithDataVolume keeps the database across restarts.
// - WithLifetime(Persistent) keeps the container running across Aspire
//   sessions so subsequent boots aren't slowed by SQL cold-start.
var sql = builder.AddSqlServer("sql")
    .WithDataVolume("analyzer-sql-data")
    .WithLifetime(ContainerLifetime.Persistent);

var analyzerDb = sql.AddDatabase("analyzerdb", databaseName: "Analyzer");

// The host Umbraco site that project-references the Analyzer RCL +
// Customizer. Aspire injects the SQL Server connection string under
// `ConnectionStrings:umbracoDbDSN` which Umbraco picks up at boot.
builder.AddProject<Projects.Analyzer_Host>("analyzer-host")
    .WithReference(analyzerDb)
    .WaitFor(analyzerDb)
    .WithEnvironment("ConnectionStrings__umbracoDbDSN", analyzerDb)
    .WithEnvironment("ConnectionStrings__umbracoDbDSN_ProviderName", "Microsoft.Data.SqlClient");

builder.Build().Run();
