namespace Analyzer.Analytics;

/// <summary>
/// One captured pageview as Analyzer observed it. Immutable. Constructed
/// once by <c>PageviewCapturedHandler</c> at notification time, surfaced
/// through <see cref="IAnalyticsEventStateProvider.CurrentRequestReceipt"/>
/// for in-process consumers that want a read-only view of the
/// current request's captured analytics state.
/// </summary>
/// <remarks>
/// <para>
/// Public + pinned. Lives in <c>Analyzer.Analytics</c> alongside
/// <see cref="IAnalyticsEventStateProvider"/> so the pinning baseline
/// captures it directly (slice-002 <c>/speckit-analyze</c> finding U2).
/// Breaking changes are PROHIBITED outside a MAJOR release
/// (Constitution Principle X).
/// </para>
/// <para>
/// The record's reference into Customizer's tables uses two distinct
/// foreign-key strategies (data-model §1):
/// <see cref="PageviewKey"/> is a <em>soft</em> reference (indexed but
/// no DB constraint — the parent <c>customizerPageview</c> row may
/// never persist under back-pressure per Customizer FR-025);
/// <see cref="VisitorProfileKey"/> is a <em>hard</em> FK to
/// <c>customizerVisitorProfile(key)</c>.
/// </para>
/// </remarks>
/// <param name="Id">
/// Opaque receipt identifier. Generated by the handler; never re-used
/// as a public identifier outside the receipt table itself.
/// </param>
/// <param name="PageviewKey">
/// Soft pointer to <c>customizerPageview.Key</c>. The same value
/// Customizer's <c>PageviewCaptured</c> notification carries on
/// <c>Pageview.Key</c>. Drives idempotency at the receipt-table level
/// (unique-index enforced).
/// </param>
/// <param name="VisitorProfileKey">
/// Hard FK to <c>customizerVisitorProfile.Key</c>. Always non-empty;
/// the handler skips notifications whose <c>VisitorProfileKey</c> is
/// <see cref="System.Guid.Empty"/> (configuration-error path).
/// </param>
/// <param name="ReceivedUtc">
/// When Analyzer observed the notification — distinct from Customizer's
/// <c>Pageview.RequestUtc</c> capture time. Sourced from the handler's
/// injected <see cref="System.TimeProvider"/>.
/// </param>
public sealed record AnalyticsEventReceipt(
    Guid Id,
    Guid PageviewKey,
    Guid VisitorProfileKey,
    DateTimeOffset ReceivedUtc)
{
    /// <summary>
    /// Slice 003 — soft FK to <c>analyzerSession.sessionKey</c>.
    /// Populated by the session resolver before the receipt is
    /// enqueued. <c>null</c> for receipts persisted by slice-002
    /// deployments — the pre-sessions cohort, intentionally not
    /// back-filled by <c>M0002</c> per FR-004.
    /// </summary>
    /// <remarks>
    /// Init-only property (NOT a positional record parameter) —
    /// preserves the slice-002 four-arg constructor signature for
    /// binary compatibility. Slice-003-and-later code constructs via
    /// <c>new AnalyticsEventReceipt(id, pvKey, visKey, utc) with
    /// { SessionKey = sessionKey }</c>. MINOR-additive per
    /// Constitution Principle X.
    /// </remarks>
    public Guid? SessionKey { get; init; }
}
